name: Main

on:
  push:
    branches:
      - master
      - "push-action/**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v5
        with:
          pnpm-version: 9

      - name: Build
        run: pnpm -r build

      - name: Lint
        run: pnpm -r lint

      - name: Test
        # The test script is moody
        uses: nick-fields/retry@v3
        with: 
          timeout_minutes: 10
          max_attempts: 5
          command: pnpm -r --workspace-concurrency=0 test:coverage

      - name: Codecov js
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: js
          directory: ./packages/js

      - name: Codecov browser
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: browser
          directory: ./packages/browser
  publish-gpr:
    needs: main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: cd packages/fastify && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.BOT_PAT}}
